version: "3.8"
services:
  bootstrap:
    image: codis/bootstrap
    build:
      context: .
      dockerfile: Dockerfile
      args:
        node_role: bootstrap
    ports:
      - "50099:50099"
    environment:
      - CODIS_IP=0.0.0.0
      - CODIS_PORT=50099
      - CODIS_USE_NODE_KEY=true
  network:
    image: codis/peer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        node_role: peer
    depends_on:
      - bootstrap
    environment:
      - CODIS_IP=0.0.0.0
      - CODIS_PORT=0
      - CODIS_PSK=${CODIS_PSK}
      - CODIS_RENDEZVOUS=${CODIS_RENDEZVOUS}
      - CODIS_CLIENT=${CODIS_CLIENT}
      - CODIS_BOOTSTRAPS=${CODIS_BOOTSTRAPS}
      - CODIS_USE_NODE_KEY=true
    deploy:
      mode: replicated
      replicas: 5
