version: "3.8"
services:

  bootstrap:
    image: codis/bootstrap
    build:
      context: .
      dockerfile: Dockerfile
      args:
        node_role: bootstrap
    environment:
      - CODIS_IP=0.0.0.0
      - CODIS_PORT=50043

  peer:
    image: codis/peer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        node_role: bootstrap
    environment:
      - CODIS_IP=0.0.0.0
      - CODIS_PORT=0
      - CODIS_PSK=${CODIS_PSK}
      - CODIS_RENDEZVOUS=${CODIS_RENDEZVOUS}
      - CODIS_CLIENT=${CODIS_CLIENT}
      - CODIS_BOOTSTRAPS=${CODIS_BOOTSTRAPS}
    depends_on:
      - bootstrap
    deploy:
      mode: replicated
      replicas: 5
